config/routes.rb
CucumberSample::Application.routes.draw do
  root :to => 'products#index'
  
  resources :makers

  resources :products

end

app/models/maker.rb
class Maker < ActiveRecord::Base
  attr_accessible :name
  has_one :porduct
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :maker_id, :name, :price, :quantity
  belongs_to :maker
  validates_presence_of :maker_id, :name, :price, :quantity
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/makers_controller.rb
class MakersController < ApplicationController
  # GET /makers
  # GET /makers.json
  def index
    @makers = Maker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @makers }
    end
  end

  # GET /makers/1
  # GET /makers/1.json
  def show
    @maker = Maker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @maker }
    end
  end

  # GET /makers/new
  # GET /makers/new.json
  def new
    @maker = Maker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @maker }
    end
  end

  # GET /makers/1/edit
  def edit
    @maker = Maker.find(params[:id])
  end

  # POST /makers
  # POST /makers.json
  def create
    @maker = Maker.new(params[:maker])

    respond_to do |format|
      if @maker.save
        format.html { redirect_to @maker, notice: 'Maker was successfully created.' }
        format.json { render json: @maker, status: :created, location: @maker }
      else
        format.html { render action: "new" }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /makers/1
  # PUT /makers/1.json
  def update
    @maker = Maker.find(params[:id])

    respond_to do |format|
      if @maker.update_attributes(params[:maker])
        format.html { redirect_to @maker, notice: 'Maker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @maker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /makers/1
  # DELETE /makers/1.json
  def destroy
    @maker = Maker.find(params[:id])
    @maker.destroy

    respond_to do |format|
      format.html { redirect_to makers_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/makers_helper.rb
module MakersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CucumberSample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/makers/_form.html.erb
<%= form_for(@maker) do |f| %>
  <% if @maker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@maker.errors.count, "error") %> prohibited this maker from being saved:</h2>

      <ul>
      <% @maker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/makers/edit.html.erb
<h1>Editing maker</h1>

<%= render 'form' %>

<%= link_to 'Show', @maker %> |
<%= link_to 'Back', makers_path %>

app/views/makers/index.html.erb
<h1>Listing makers</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @makers.each do |maker| %>
  <tr>
    <td><%= maker.name %></td>
    <td><%= link_to 'Show', maker %></td>
    <td><%= link_to 'Edit', edit_maker_path(maker) %></td>
    <td><%= link_to 'Destroy', maker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Maker', new_maker_path %>

app/views/makers/new.html.erb
<h1>New maker</h1>

<%= render 'form' %>

<%= link_to 'Back', makers_path %>

app/views/makers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @maker.name %>
</p>


<%= link_to 'Edit', edit_maker_path(@maker) %> |
<%= link_to 'Back', makers_path %>

app/views/products/.#_form.html.erb
k2works@MacBook-Air.local.8724

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :maker_id %><br />
    <%= f.collection_select 'maker_id',Maker.find(:all),:id, :name, { :include_blank => true} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
    <th><%= link_to 'Maker', makers_path %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.price %></td>
    <td><%= product.quantity %></td>
    <td><%= product.maker.name %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<p>
  <b>Quantity:</b>
  <%= @product.quantity %>
</p>

<p>
  <b>Maker:</b>
  <%= @product.maker_id %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>